"""empty message

Revision ID: 83fe65509473
Revises: b6a90f49a0f3
Create Date: 2023-10-16 02:00:47.461559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83fe65509473'
down_revision = 'b6a90f49a0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_starship')
    op.drop_table('starship')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starship',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('starship_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('cost_in_credits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_atmosphering_speed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crew', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passengers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cargo_capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('consumables', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('hyperdrive_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('starship_class', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pilots', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='starship_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('favorite_starship',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('starship_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['starship_id'], ['starship.id'], name='favorite_starship_starship_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_starship_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_starship_pkey')
    )
    # ### end Alembic commands ###
